### ISSUE TITLE
Error for 2-node, 1-tie network of class `igraph`

### ISSUE THREAD

**Issue by instantkaffee** [briatte/ggnetwork#12]
```
g= igraph::random.graph.game(n = 2, p.or.m = 1)
ggnetwork::ggnetwork(g)
```

throughs in Version 0.5.1:

```
Error in if (nrow(edges[, 1:2]) > nrow(unique(edges[, 1:2]))) { : 
  argument is of length zero
```

I think `g` is a valid Input for ggnetwork.
Any fix ?

**Comment by instantkaffee** [comment]
Hello @briatte , when do you think that a fix become available?

**Comment by martinritchie** [comment]
@instantkaffee I am running into the same problem, did you ever find a work around?

**Comment by instantkaffee** [comment]
@martinritchie No, I was hoping for a fix from @briatte

**Comment by kgero** [comment]
I'm also looking for a fix.

**Comment by fmusili** [comment]
@briatte ,Please fix the bug.Am getting the same error and its hindering my visualizations.

**Comment by martinritchie** [comment]
I think I have a fix, I will submit a pull request tomorrow.

**Comment by instantkaffee** [comment]
@martinritchie is your fix accepted?

**Comment by martinritchie** [comment]
Sorry for the slow reply. I noticed that there is already a pull requuest that fixes this issue. Have a look, it is quite easy to implement yourself whilst you wait for the pull to be approved.

**Comment by briatte** [comment]
This issue still looks alive, despite PR #20. Package might need PR #24 after all.

``` r
# 2-node, 1-edge network
g <- igraph::random.graph.game(n = 2, p.or.m = 1)

# fails
ggnetwork(g)
#> Error in ggnetwork(g): could not find function "ggnetwork"
# fails
fortify.igraph(g) 
#> Error in fortify.igraph(g): could not find function "fortify.igraph"

# ... but if converted to just a matrix
m <- as.matrix(igraph::as_adjacency_matrix(g))
# works
ggnetwork(m)
#> Error in ggnetwork(m): could not find function "ggnetwork"
# works
ggplot(ggnetwork(m), aes(x, y, xend = xend, yend = yend)) +
  geom_nodes() +
  geom_edges()
#> Error in ggplot(ggnetwork(m), aes(x, y, xend = xend, yend = yend)): could not find function "ggplot"

# ... same if converted to network
n <- network::network(m, directed = FALSE)
# works
ggnetwork(n)
#> Error in ggnetwork(n): could not find function "ggnetwork"
# works
fortify.network(n)
#> Error in fortify.network(n): could not find function "fortify.network"
# works
ggplot(ggnetwork(n), aes(x, y, xend = xend, yend = yend)) +
  geom_nodes() +
  geom_edges()
#> Error in ggplot(ggnetwork(n), aes(x, y, xend = xend, yend = yend)): could not find function "ggplot"
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by briatte** [comment]
All apologies for the long wait one this issue… !

**Comment by komalsrathi** [comment]
Hi! 

I just got this error with version 0.5.1. Was this resolved?

Thanks
Komal

**Comment by briatte** [comment]
Hi @komalsrathi 

Yes, that issue is solved, but in the development branch so far -- please reinstall the package from GitHub to solve the issue:

```r
remotes:install_github("briatte/ggnetwork")
```

CRAN submission is late but will happen soon.
