### ISSUE TITLE
Support multiple edges

### ISSUE THREAD

**Issue by emillykkejensen** [briatte/ggnetwork#17]
Is there a way or are you planing to implement a way to show multiple edges between the same nodes?

**Comment by emillykkejensen** [comment]
Hate when it happens, but just when I hit "Comment" I realized, that it is pretty simple. I just need as many geom_edges as I have different edges I what to show, then subset each and have different curvatures for them. So if anyone else want to show more than one edge between two nodes, that’s the way to do it :-)

**Comment by briatte** [comment]
Although it is not flexible to variable number of multiple edges, that's a solution indeed, and it will have to do, since I do not see an easy way to implement the feature in any other way that would not create even more redundancy in the data structure used by the package.

**Comment by emillykkejensen** [comment]
Don't know if it is posible or practical - but what if curvature was part of the mapping?

**Comment by briatte** [comment]
I do not think it is possible – `curvature` in [`geom_segment`](http://docs.ggplot2.org/current/geom_segment.html) seems fixed. Furthermore, it would pose, I guess, some interesting computational issues.
