### ISSUE TITLE
Can't handle networks with no edges

### ISSUE THREAD

**Issue by mhairi** [briatte/ggnetwork#19]
If I make a network with only nodes, no edges

```
library(ggplot2)
library(network)
library(ggnetwork)

D <- matrix(c(1, 0, 0,
              0, 1, 0,
              0, 0, 1),
            nrow = 3,
            ncol = 3)

net <- network(D)
```

Then ggnetwork can't convert this to a dataframe:

```
> ggnetwork(net)
Error in xj[i, , drop = FALSE] : subscript out of bounds
```

**Comment by mcanouil** [comment]
Hi,
I updated my pull request #20 to include a fix for this problem. It should works most of the time. I didn't account for any nodes/edges attributes.

**Comment by mhairi** [comment]
Thank you very much!

**Comment by briatte** [comment]
@mhairi First of all, all apologies for not answering earlier — and yes, thanks to @mcanouil, this problem is now solved.
