### ISSUE TITLE
Legends not appearing in ggnet2 plot along with wrong color for edges

### ISSUE THREAD

**Issue by FinScience** [briatte/ggnetwork#21]
I need to create a network plot where the color of nodes and edges will be dependent on a parameter. Though I have been able to render the graph, the color of edges are not reflecting properly and the legend is also not appearing. 

Below is a reproducible code. Any help would be great.

        library(network)
        library(sna)
        library(ggplot2)
        library(ggnetwork)
        library(sna)
        library(GGally)

       edge_df = data.frame("Start" = c(1,2,4,5), "End" = c(2,3,3,1), "strength" = 
        c("uncovered","uncovered","covered","uncovered"))

        vertex_df = data.frame("Nodes" = c(1,2,3,4,5), "strength" = 
        c("covered","uncovered","uncovered",                                                                             
        "uncovered","covered"))

        net = network(edge_df[,1:2], directed = FALSE)

        net %v% "nodes" = ifelse(vertex_df$strength == "covered", "Nodes Covered", 
        "Nodes Uncovered")

        net %v% "color_node" = ifelse(net %v% "nodes" == "Nodes Covered", 
        "steelblue", "yellow")

        net %e% "weight" = ifelse(edge_df$strength == "covered", "Edges Covered", 
        "Edges Uncovered")

       set.edge.attribute(net, "color", ifelse(net %e% "weight" == "Edges Covered", 
       "green", "red"))

        set.seed(123)
        ggnet2(net, color = "color_node",
        edge.color = "color", 
        edge.size = 0.5,
        node.size = 1,
        mode = "fruchtermanreingold",
        color.legend = c("timers","weight")) +
        theme(panel.background = element_rect(fill = "black"),
        text = element_text(color = "white"),
        legend.position = "bottom")

**Comment by briatte** [comment]
Hi @FinScience 

All apologies for not answering this earlier.

This issue should go in the [`ggnet`](https://github.com/briatte/ggnet) repository: if you are still facing it, please post it there.
