### ISSUE TITLE
Can't pre-calculate the node locations

### ISSUE THREAD

**Issue by jfaganUK** [briatte/ggnetwork#22]
Using igraph, I calculated the x and y locations of the nodes first. I plan on making a series of charts, but for easy comparison I want make sure the nodes are in the same location each time I make a chart.

```{r}
g13.r.lo <- layout_nicely(g13.r)
V(g13.r)$x <- g13.r.lo[,1]
V(g13.r)$y <- g13.r.lo[,2]
```

But when I use ```ggnetwork``` it returns an error:

```
> ggplot(g13.r, arrow.gap = 0.01, aes(x, y, xend = xend, yend = yend)) +
+   geom_edges(alpha = 0.3) +
+   geom_nodes(aes(color = legacy)) +
+   scale_color_discrete('Context') +
+   theme_blank()
Error in fix.by(by.x, x) : 'by' must specify uniquely valid columns
```

**Comment by briatte** [comment]
Hi @jfaganUK 

All apologies for answering so very, very late.

If you are still facing the issue, try installing the development version of `ggnetwork` from this repository:

```r
# with `remotes`
remotes::install_github("briatte/ggnetwork")
# or with `devtools`
devtools::install_github("briatte/ggnetwork")
```

This solves the issue, as shown by the code below, which indeed fails with the CRAN version of the package, but which works with the current (development, patched-for-native-`igraph`-support) GitHub version.

```r
library(igraph)
library(ggnetwork)

n <- igraph::random.graph.game(10, p.or.m = "p")
V(n)$legacy <- sample(c("a", "b"), 10, replace = TRUE)

l <- layout_nicely(n)
V(n)$xcoord <- l[,1]
V(n)$ycoord <- l[,2]

ggplot(n, arrow.gap = 0.01, aes(x, y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.3) +
  geom_nodes(aes(color = legacy)) +
  scale_color_discrete('Context') +
  theme_blank()
```

The current development version will be on CRAN by the end of the summer.

Again, all apologies for not answering earlier.
