### ISSUE TITLE
color edges by weights

### ISSUE THREAD

**Issue by nick-youngblut** [briatte/ggnetwork#23]
Maybe I'm just missing this feature when looking through the documentation, but can `ggnetwork` be used to *easily* plot edge colors by weights (eg., strong positive colored bright green; strong negative colored bright red; values within the extremes colors by a gradient)? 

I haven't seen an example network like that in the vignette, and I haven't seen any examples of that in the documentation. 

To be clear, I've just tried creating ggnetwork objects (data.frames) by inputing a symmetric matrix of interactions.

**Comment by briatte** [comment]
Hi @nick-youngblut 

All apologies for not answering your question earlier.

The answer is yes, and I hope that you found the answer in the vignette, which sows several examples of edge coloring based on any attribute, edge weights included.

Minimal example below:

```r
library(igraph)
library(ggnetwork)

n <- igraph::random.graph.game(10, 0.3)
E(n)$weight <- sample(c(1, 2), igraph::gsize(n), replace = TRUE)

# continuous version
ggplot(n, aes(x, y, xend = xend, yend = yend)) +
  geom_edges(aes(color = weight)) +
  geom_nodes() +
  theme_blank()

# discrete version
ggplot(n, aes(x, y, xend = xend, yend = yend)) +
  geom_edges(aes(color = factor(weight))) +
  geom_nodes() +
  theme_blank()
```
