### ISSUE TITLE
Submit v0.5.8 to CRAN

### ISSUE THREAD

**Issue by briatte** [briatte/ggnetwork#39]
- [x] Check that https://github.com/briatte/ggnetwork/issues/33 is still solved
- [x] Update NEWS, see #38 
- [x] Update README
  - _R Journal_ article
  - Extended thanks
- [x] Add @jcfisher, @mbojan and @trinker as contributors in DESCRIPTION
- [x] Switch DESCRIPTION to UTF-8
- [ ] [HAL-SHS](https://halshs.archives-ouvertes.fr/) entry
- [x] GitHub release
- [x] Inform contributors and people in threads
  - https://github.com/briatte/ggnetwork/issues/14
  - https://github.com/csbl-usp/CEMiTool/issues/18
- [x] Travis CI?
- [x] Badges?

**Comment by briatte** [comment]
Hi @jcfisher @mbojan @trinker 

I'm getting ready to update `ggnetwork` after years of neglect.

The DESCRIPTION now has your names as contributors: https://github.com/briatte/ggnetwork/commit/f21a63ef60699edcdfc20cab28dfe767867082aa — please let me know if you want me to change anything to what I have included, e.g. "Jacob C." to "Jake", or adding an ORCID identifier.

I'm also going to reference the package on a French repository, [HAL-SHS](https://halshs.archives-ouvertes.fr/): here's an [example software entry](https://halshs.archives-ouvertes.fr/halshs-01925193). For that, I'd like your permission to include the following formation about you:

- @mbojan – Michał Bojanowski, Kozminski University, https://github.com/mbojan
- @trinker – Tyler Rinker, Campus Labs, https://github.com/trinker
- @jcfisher – Jacob C. Fisher, University of Michigan [Ann Arbor], https://github.com/jcfisher

Let me know if I got the affiliations right, and if you prefer including an academic Web page (or even a personal homepage) instead of your GitHub URLs.

Thanks!

**Comment by briatte** [comment]
@mcanouil same question as above: Mickaël Canouil, University of Lille (?), https://github.com/mcanouil

**Comment by briatte** [comment]
Hi @kippjohnson

Same question as in first post: Kipp Johnson, Icahn School of Medicine at Mount Sinai, https://github.com/kippjohnson

**Comment by kippjohnson** [comment]
@briatte Thank you very much for including me for my small PR, that is very kind of you. I will try to keep helping in the future as I use your package a lot.

**Comment by jcfisher** [comment]
@briatte What you have listed for me is great, too.  Thanks!

**Comment by mcanouil** [comment]
> Same question as above: Mickaël Canouil, University of Lille (?), https://github.com/mcanouil

@briatte I have several affiliations, but you can use my main one: "Institut Pasteur de Lille".
Thank you for adding to the contributors.

**Comment by briatte** [comment]
Might also be adding @zachcp, Laboratory of Genetically Encoded Small Molecules, The Rockefeller University, New York, NY, USA, https://github.com/zachcp

**Comment by briatte** [comment]
CRAN: https://cran.r-project.org/package=ggnetwork
HAL-SHS: halshs-02476719 (link forthcoming)
ORCID: https://orcid.org/0000-0001-6494-9774 (no idea how to add co-authors)
