### ISSUE TITLE
Require R ≥ 3.5 to avoid Travis CI build fails

### ISSUE THREAD

**Issue by briatte** [briatte/ggnetwork#45]
The package imports `sna`, which in turn imports [`statnet.common`](https://cran.r-project.org/package=statnet.common). Unfortunately, `statnet.common` 4.2.0+ now [requires R ≥ 3.5](https://cran.r-project.org/web/packages/statnet.common/news/news.html):

> statnet.common now depends on >= 3.5 due to what appears to be a method dispatching bug in earlier versions.

@mcanouil Can I ask how you determined the package could work with R ≥ 3.1, please? Do you think I should modify both the `.travis.yml` and the `DESCRIPTION` file, or just the former?

**Comment by briatte** [comment]
@mcanouil I'm closing because I edited the `.travis.yml` file, but:

- Can I ask how you determined the package could work with R ≥ 3.1, please?
- Do you think I should modify both the `.travis.yml` and the `DESCRIPTION` file, or just the former?

**Comment by mcanouil** [comment]
@briatte just by looking at the log files from travis.

https://travis-ci.org/briatte/ggnetwork/builds/562651756 for the build from this morning

If you cannot "fix" the travis checks from early R version, then the requirement of your `DESCRIPTION` should be updated accordingly (welcome to the packages dependencies world^^).

**Comment by briatte** [comment]
Yep. As long as the package uses `sna`, which it needs for graph layouts on `network` objects, it will support only R ≥ 3.5.

I'm going to have questions like that for a few days but will then stop, I promise :)

**Comment by mcanouil** [comment]
> I'm going to have questions like that for a few days but will then stop, I promise :)

On me, I should not have contributed ^^
