### ISSUE TITLE
Node-faceting

### ISSUE THREAD

**Issue by aterhorst** [briatte/ggnetwork#7]
Hello,

I have multiple directed network objects (e.g. net1, net2, net3, ...) each with same number of nodes and node attributes. Only the edges are different (edges represent different relationships). The example provided in https://briatte.github.io/ggnetwork/#node-faceting appears to have only one network object. The output is exactly what I am after. I simply do not know how to deal with separate/multiple network objects. Please advise.

**Comment by aterhorst** [comment]
Perhaps I need to combine the networks into one network object. Then use network name as a facet variable. I will look into this.

**Comment by briatte** [comment]
Would you mind providing your data by using `dput()` and dumping the content somewhere, e.g. as a Gist or on Pastebin?

**Comment by aterhorst** [comment]
Sure. I have never used dput() before but seems straight-forward.


What I will do is provide 2x network objects. I will also provide my R script used to plot one network object. Will do so when I am in the office tomorrow. Thanks a ton.


--
Andrew Terhorst
Open Innovation Researcher
Location leader for Sandy Bay site

DATA61 |  CSIRO
E andrew.terhorst@csiro.au T +61 3 6237 5662 M +61 400 869 594
15 College Rd, Sandy Bay, TAS 7005
http://www.data61.csiro.au
http://people.csiro.au/T/A/Andrew-Terhorst.aspx
________________________________

**Comment by aterhorst** [comment]
Hi Francoisn

Here we go:

https://gist.github.com/aterhorst/fd3f9eeead8104feb5a382dbfd93522d


There are three files:


  *   net1.dput.txt (knowledge sharing network, with weighted edge variable = “tacit”)
  *   net2.dput.txt (idea generation network, without any weight variables)
  *   Ggnetwork.R (script I use to generate plot below).

[cid:A15DEF92-4A75-4278-8A43-906A3DB34666]


I hope this is sufficient for you.

Essentially I want node placement for net2 (and net3 …net9) to be same as net1 one 3 x 3 plot layout (as an example).

Thanks for your help!

Cheers
--
Andrew Terhorst<http://people.csiro.au/T/A/Andrew-Terhorst.aspx>
Open Innovation Researcher
Sandy Bay Location Leader

DATA61 | CSIRO
E andrew.terhorst@data61.csiro.au<mailto:andrew.terhorst@data61.csiro.au> T +613 6237 5562   M +61 400 869 594
15 College Road, Sandy Bay, TAS 7005 www.data61.csiro.au<http://www.data61.csiro.au/>
research.csiro.au/innovation<http://research.csiro.au/innovation>

CSIRO’s Digital Productivity business unit and NICTA have joined forces to create digital powerhouse Data61
[cid:075BEAE4-C33C-4EDA-86DB-E848A66C8083]

**Comment by aterhorst** [comment]
[networks.pdf](https://github.com/briatte/ggnetwork/files/292626/networks.pdf)

Here is example what I am after generated using ggnet.

**Comment by briatte** [comment]
Hi @aterhorst 

I have to apologise for letting this issue slip. I hope you have found a workaround, possibly by using something like the `patchwork` package to combine several plots into one. The package did not exist in 2016, so the solution at the time might have been using the `grid` package, although it is not the easiest package to use.

Again, very sorry that I let your question slip. Best,

François
