### ISSUE TITLE
Incompatibility with dev igraph

### ISSUE THREAD

**Issue by krlmlr** [briatte/ggnetwork#74]
We are in the process of releasing igraph 1.6.0. The ggnetwork package fails its checks with our update due to `fortify()` being too strict. This is fairly critical because five other packages depend on this.

Submitting a PR in a few minutes. Can you please send an update to CRAN at your earliest convenience?

Tracker: https://github.com/igraph/rigraph/issues/968.

## igraph 1.5.99.9xxx

``` r
library(ggnetwork)
#> Loading required package: ggplot2

g <- igraph::graph_from_literal(a -+ b)
fortify(g, layout = diag(2))
#> Error in fortify.igraph(g, layout = diag(2)): layout matrix dimensions do not match network size
```

<sup>Created on 2023-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## igraph 1.5.1

``` r
library(ggnetwork)
#> Loading required package: ggplot2

g <- igraph::graph_from_literal(a -+ b)
fortify(g, layout = diag(2))
#>    x y name       xend      yend
#> 2  1 0    a 0.01767767 0.9823223
#> 1  1 0    a 1.00000000 0.0000000
#> 21 0 1    b 0.00000000 1.0000000
```

<sup>Created on 2023-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
I never mentioned that we're releasing igraph 1.6.0 in early December. Hope it works out, sorry for the rush.

**Comment by krlmlr** [comment]
@briatte: I'm pushing to CRAN on Wednesday. If you can get in your update earlier, it will save me and five other maintainers some cycles. Thank you.

**Comment by krlmlr** [comment]
We're planning to send igraph to CRAN on January 23.

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by adrientaudiere** [comment]
Hi @krlmlr and @briatte,
I wonder if you have a date for a cran release including this important change in fortify. For the moment, I can use the dev version of ggnetwork, but I want to submit my package ([MiscMetabar](https://github.com/adrientaudiere/MiscMetabar)) to bioconductor, so I need package dependencies on either CRAN or bioconductor.  
Thanks for your work.
