### ISSUE TITLE
Edge label coordinates

### ISSUE THREAD

**Issue by mbojan** [briatte/ggnetwork#8]
Thanks for this awesome package!

I would like to place small icon-like images (`png`) on/near edge labels. Perhaps a bit like `*repel`. Is there a way to get my hands on the coordinates of the labels so I can add them e.g. like [here](http://stackoverflow.com/questions/9917049/inserting-an-image-to-ggplot2)?

**Comment by briatte** [comment]
If you save your plot as object `p` and then ask for `p$data`, you should get the mid-edge coordinates in the return, as long as they have been set (i.e. as long as you have sent something to plot at mid-edges).

**Comment by mbojan** [comment]
Great, thanks!

Are you at http://eusn2016.sciencesconf.org/ by any chance?

**Comment by briatte** [comment]
I'm in Paris, not very far from EUSN – email me at f.briatte (at) Google Mail if you wanna meet :)
