### ISSUE TITLE
Unexpected loading and attaching sna

### ISSUE THREAD

**Issue by mbojan** [briatte/ggnetwork#9]
`fortify.network` unexpectedly loads and attaches the "sna" package even though "sna" is declared only as import. That might ruin your workspace because of several name conflicts. 

IMHO `load_pkg` is a rather nasty hack with  even nastier side effects ;) I think it is only needed once to call an appropriate layout algorithm from "sna".

I will submit a PR.

**Comment by briatte** [comment]
Fixed by #10.
